services:
  docs:
    image: real_state_manager_local_docs
    container_name: real_state_manager_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./real_state_manager:/app/real_state_manager:z
    ports:
      - '9000:9000'
    command: /start-docs
